export enum ErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_DISABLED = "USER_DISABLED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
  TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED",
  TWO_FACTOR_INVALID = "TWO_FACTOR_INVALID",
  WEBAUTHN_FAILED = "WEBAUTHN_FAILED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT = "INVALID_FORMAT",
  INVALID_PHONE = "INVALID_PHONE",
  INVALID_EMAIL = "INVALID_EMAIL",
  DUPLICATE_USER = "DUPLICATE_USER",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  ODOO_UNAVAILABLE = "ODOO_UNAVAILABLE",
  POSTING_FAILED = "POSTING_FAILED",

  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",

  FORBIDDEN = "FORBIDDEN",
  CONFLICT = "CONFLICT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  MISSING_API_KEY = "MISSING_API_KEY",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  STORAGE_ERROR = "STORAGE_ERROR",
  ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND",
  MAX_TRANSACTION_ATTACHMENTS_EXCEEDED = "MAX_TRANSACTION_ATTACHMENTS_EXCEEDED",
  PROFILE_IMAGE_NOT_FOUND = "PROFILE_IMAGE_NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  OLD_PASSWORD_SAME_AS_NEW = "OLD_PASSWORD_SAME_AS_NEW",
  OLD_PASSWORD_INCORRECT = "OLD_PASSWORD_INCORRECT",

  /**
   * workday errors
   */
  WORKDAY_NOT_FOUND = "WORKDAY_NOT_FOUND",
  WORKDAY_NOT_OPENED = "WORKDAY_NOT_OPENED",
  WORKDAY_ALREADY_OPENED = "WORKDAY_ALREADY_OPENED",
  YOU_HAVE_AN_OPEN_WORKDAY = "YOU_HAVE_AN_OPEN_WORKDAY",

  /**
   * invalid transactions
   */
  INVALID_TRANSACTION_AMOUNT = "INVALID_TRANSACTION_AMOUNT",
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  INVALID_USER_ID = "INVALID_USER_ID",
  INVALID_WORKDAY_ID = "INVALID_WORKDAY_ID",
  INVALID_TRANSACTION_ID = "INVALID_TRANSACTION_ID",

  /**
   * resources
   */
  INVALID_RESOURCE_ID = "INVALID_RESOURCE_ID",
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
}

